routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'laravel-filemanager'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
Route::get('robots.txt', 'RobotsController');
Route::get('sitemap', 'HomeController@sitemap');

Route::name('home')->get('/', 'HomeController@index');
Route::name('404')->get('/404', 'HomeController@notFound');
Route::name('empreendimentos')->get('empreendimentos', 'EmpController@index');
Route::name('emp')->get('empreendimentos/{slug}', 'EmpController@slug');
Route::name('emp.download')->get('empreendimentos/{slug}/download', 'EmpController@download');
Route::name('emp.contact')->post('empreendimentos/{slug}/contato', 'EmpController@contact');
Route::name('about')->get('/sobre', 'AboutController@index');
Route::name('builder')->get('/monteoseu', 'BuilderController@index');
Route::name('contact')->get('/contato', 'ContactController@index');
Route::name('contact.send')->post('/contato', 'ContactController@store');

Route::name('conteudo')->get('conteudos/{slug}', 'ConteudosController@slug');
Route::name('conteudos')->get('conteudos', 'ConteudosController@index');

Auth::routes(['register' => false]);

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('panel');

    Route::prefix('home')->name('home.')->group(function () {
        Route::get('create', 'AdminController@create')->name('create');
        Route::post('store', 'AdminController@store')->name('store');
        Route::post('{id}/destroy', 'AdminController@destroy')->name('destroy');
        Route::get('{id}', 'AdminController@show')->name('show');
        Route::post('{id}', 'AdminController@update')->name('update');
        Route::get('/', 'AdminController@home')->name('index');
    });
    Route::prefix('destaques')->name('feat.')->group(function () {
        Route::get('create', 'FeatureController@create')->name('create');
        Route::post('store', 'FeatureController@store')->name('store');
        Route::post('{id}/destroy', 'FeatureController@destroy')->name('destroy');
        Route::get('{id}', 'FeatureController@show')->name('show');
        Route::post('{id}', 'FeatureController@update')->name('update');
        Route::get('/', 'FeatureController@index')->name('index');
    });
    Route::prefix('empreendimentos')->name('emp.')->group(function () {
        Route::get('create', 'EmpController@create')->name('create');
        Route::post('store', 'EmpController@store')->name('store');
        Route::post('{id}/destroy', 'EmpController@destroy')->name('destroy');
        Route::get('{id}', 'EmpController@show')->name('show');
        Route::post('{id}', 'EmpController@update')->name('update');
        Route::get('/', 'EmpController@admin')->name('admin');

        Route::get('{emp}/fotos/create', 'EmpPhotoController@create')->name('photo.create');
        Route::post('{emp}/fotos/store', 'EmpPhotoController@store')->name('photo.store');
        Route::post('{emp}/fotos/{id}/destroy', 'EmpPhotoController@destroy')->name('photo.destroy');
        Route::get('{emp}/fotos/{id}', 'EmpPhotoController@show')->name('photo.show');
        Route::post('{emp}/fotos/{id}', 'EmpPhotoController@update')->name('photo.update');
        Route::get('{emp}/fotos', 'EmpPhotoController@index')->name('photo.index');

        Route::get('{emp}/pavimentos/create', 'EmpFloorController@create')->name('floor.create');
        Route::post('{emp}/pavimentos/store', 'EmpFloorController@store')->name('floor.store');
        Route::post('{emp}/pavimentos/{id}/destroy', 'EmpFloorController@destroy')->name('floor.destroy');
        Route::get('{emp}/pavimentos/{id}', 'EmpFloorController@show')->name('floor.show');
        Route::post('{emp}/pavimentos/{id}', 'EmpFloorController@update')->name('floor.update');
        Route::get('{emp}/pavimentos', 'EmpFloorController@index')->name('floor.index');

        Route::get('{emp}/pagamentos/create', 'EmpPaymentController@create')->name('payment.create');
        Route::post('{emp}/pagamentos/store', 'EmpPaymentController@store')->name('payment.store');
        Route::post('{emp}/pagamentos/{id}/destroy', 'EmpPaymentController@destroy')->name('payment.destroy');
        Route::get('{emp}/pagamentos/{id}', 'EmpPaymentController@show')->name('payment.show');
        Route::post('{emp}/pagamentos/{id}', 'EmpPaymentController@update')->name('payment.update');
        Route::get('{emp}/pagamentos', 'EmpPaymentController@index')->name('payment.index');
    });

    Route::prefix('pins')->name('pin.')->group(function () {
        Route::get('create', 'PinController@create')->name('create');
        Route::post('store', 'PinController@store')->name('store');
        Route::post('{id}/destroy', 'PinController@destroy')->name('destroy');
        Route::get('{id}', 'PinController@show')->name('show');
        Route::post('{id}', 'PinController@update')->name('update');
        Route::get('/', 'PinController@index')->name('index');

        Route::get('{pin}/ad/create', 'PinAdController@create')->name('ad.create');
        Route::post('{pin}/ad/store', 'PinAdController@store')->name('ad.store');
        Route::post('{pin}/ad/{id}/destroy', 'PinAdController@destroy')->name('ad.destroy');
        Route::get('{pin}/ad/{id}', 'PinAdController@show')->name('ad.show');
        Route::post('{pin}/ad/{id}', 'PinAdController@update')->name('ad.update');
        Route::get('{pin}/ad', 'PinAdController@index')->name('ad.index');
    });

    Route::prefix('pavimentos')->name('unity.')->group(function () {
        Route::get('{floor}/unidades/create', 'EmpFloorUnityController@create')->name('create');
        Route::post('{floor}/unidades/store', 'EmpFloorUnityController@store')->name('store');
        Route::post('{floor}/unidades/{id}/destroy', 'EmpFloorUnityController@destroy')->name('destroy');
        Route::get('{floor}/unidades/{id}', 'EmpFloorUnityController@show')->name('show');
        Route::post('{floor}/unidades/{id}', 'EmpFloorUnityController@update')->name('update');
        Route::get('{floor}/unidades', 'EmpFloorUnityController@index')->name('index');
    });

    Route::prefix('unidades')->name('planned.')->group(function () {
        Route::get('{p}/planejados/create', 'EmpFloorUnityPlannedController@create')->name('create');
        Route::post('{p}/planejados/store', 'EmpFloorUnityPlannedController@store')->name('store');
        Route::post('{p}/planejados/{id}/destroy', 'EmpFloorUnityPlannedController@destroy')->name('destroy');
        Route::get('{p}/planejados/{id}', 'EmpFloorUnityPlannedController@show')->name('show');
        Route::post('{p}/planejados/{id}', 'EmpFloorUnityPlannedController@update')->name('update');
        Route::get('{p}/planejados', 'EmpFloorUnityPlannedController@index')->name('index');
    });

    Route::prefix('blog')->name('blog.')->group(function () {
        Route::get('create', 'BlogController@create')->name('create');
        Route::post('store', 'BlogController@store')->name('store');
        Route::post('{id}/destroy', 'BlogController@destroy')->name('destroy');
        Route::get('{id}', 'BlogController@show')->name('show');
        Route::post('{id}', 'BlogController@update')->name('update');
        Route::get('/', 'BlogController@index')->name('index');
    });

    Route::prefix('contatos')->name('contact.')->group(function () {
        Route::get('create', 'ContactController@create')->name('create');
        Route::post('store', 'ContactController@store')->name('store');
        Route::post('{id}/destroy', 'ContactController@destroy')->name('destroy');
        Route::get('{id}/simulation', 'ContactController@simulation')->name('simulation');
        Route::get('{id}', 'ContactController@show')->name('show');
        Route::post('{id}', 'ContactController@update')->name('update');
        Route::get('/', 'ContactController@admin')->name('admin');
    });

    Route::prefix('eletros')->name('electro.')->group(function () {
        Route::get('create', 'ElectroController@create')->name('create');
        Route::post('store', 'ElectroController@store')->name('store');
        Route::post('{id}/destroy', 'ElectroController@destroy')->name('destroy');
        Route::get('{id}', 'ElectroController@show')->name('show');
        Route::post('{id}', 'ElectroController@update')->name('update');
        Route::get('/', 'ElectroController@index')->name('index');
    });

    Route::prefix('sobre')->name('about.')->group(function () {
        Route::get('create', 'AboutController@create')->name('create');
        Route::post('store', 'AboutController@store')->name('store');
        Route::post('{id}/destroy', 'AboutController@destroy')->name('destroy');
        Route::get('{id}', 'AboutController@show')->name('show');
        Route::post('{id}', 'AboutController@update')->name('update');
        Route::get('/', 'AboutController@admin')->name('admin');
    });
});

app/EmpPhoto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmpPhoto extends Model
{
    protected $table = 'emp_photos';
    
    protected $fillable = [
        'emp_id',
        'order',
        'type',
        'img',
        '1tt',
        '1stt',
        '2tt',
        '2stt',
        '3tt',
        '3stt',
        '4tt',
        '4stt',
        '5tt',
        '5stt',
        '6tt',
        '6stt',
    ];

    public function scopeOrder($query)
    {
        return $query->orderBy('order', 'asc');
    }
}

app/Http/Controllers/EmpPhotoController.php
<?php

namespace App\Http\Controllers;

use App\Emp;
use App\EmpPhoto;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class EmpPhotoController extends Controller
{
    protected $emp;
    protected $empPhoto;

    public function __construct(Emp $emp, EmpPhoto $ep) {
        $this->middleware('auth');
        $this->emp = $emp;
        $this->empPhoto = $ep;
    }

    public function index($emp)
    {
        $data = $this->emp->find($emp)->photos()->order()->paginate();

        return view('admin.empPhoto.index', compact('data', 'emp'));
    }

    public function create($emp)
    {        
        return view('admin.empPhoto.create', compact('emp'));
    }

    public function store($emp, Request $request)
    {
        $input = $request->all();

        $imageName = time().'.'.$input['img']->extension();
        $input['img']->move(public_path('storage/emp'), $imageName);
        $input['img'] = $imageName;
        
        $this->emp->find($emp)->photos()->create($input);

        toastr()->success('Registro Salvo');

        return redirect()->route('admin.emp.photo.index', $emp);
    }

    public function show($emp, $id)
    {
        $data = $this->empPhoto->find($id);

        return view('admin.empPhoto.edit', compact('data', 'emp'));
    }

    public function update($emp, $id, Request $request)
    {
        $input = $request->all();
        if (isset($input['img'])) {
            $imageName = time().'.'.$input['img']->extension();
            $input['img']->move(public_path('storage/emp'), $imageName);

            $input['img'] = $imageName;
        } else {
            unset($input['img']);
        }
        
        $this->empPhoto->find($id)->update($input);

        toastr()->success('Registro Atualizado');

        return redirect()->route('admin.emp.photo.index', $emp);
    }

    public function destroy($emp, $id)
    {
        $this->empPhoto->find($id)->delete();

        toastr()->success('Registro Apagado');

        return redirect()->route('admin.emp.photo.index', $emp);
    }
}

resources/views/admin/empPhoto/_form.blade.php
<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('type', 'Status', ['class' => '']) !!}
    {!! Form::select('type', [
      'Interna' => 'Interna',
      'Externa' => 'Externa',
      'Planta' => 'Planta',
    ],old('type'), ['class' => 'form-control', 'requred']) !!}
  </div>
</div>

<div class="col-sm-12 col-md-2">
  <div class="form-group mb-2">
    {!! Form::label('order', 'Ordem', ['class' => '']) !!}<br>
    {!! Form::number('order', old('order'), ['class' => 'form-control', 'required']) !!}
  </div>
</div>

<div class="col-sm-12 col-md-4">
  <div class="form-group mb-4">
    {!! Form::label('img', 'Imagem', ['class' => '']) !!}<br>
    @if(isset($data) && $data->ch_img) <img src="{{url('storage/emp/'.$data->ch_img)}}" width="50px" height="30px" style="margin-bottom: 5px;"> @endif
    {!! Form::file('img', old('img'), ['class' => 'form-control', 'required']) !!}
  </div>
</div>

<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('1tt', 'Superior 1', ['class' => '']) !!}
    {!! Form::text('1tt', old('1tt'), ['class' => 'form-control']) !!}
    @if($errors->has('1tt'))
      <span class="text-danger">{{ $errors->first('1tt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('1stt', 'Legenda', ['class' => '']) !!}
    {!! Form::text('1stt', old('1stt'), ['class' => 'form-control']) !!}
    @if($errors->has('1stt'))
      <span class="text-danger">{{ $errors->first('1stt') }}</span>
    @endif
  </div>
</div>
<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('2tt', 'Superior 2', ['class' => '']) !!}
    {!! Form::text('2tt', old('2tt'), ['class' => 'form-control']) !!}
    @if($errors->has('2tt'))
      <span class="text-danger">{{ $errors->first('2tt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-22 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('2stt', 'Legenda', ['class' => '']) !!}
    {!! Form::text('2stt', old('2stt'), ['class' => 'form-control']) !!}
    @if($errors->has('2stt'))
      <span class="text-danger">{{ $errors->first('2stt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('3tt', 'Superior 3', ['class' => '']) !!}
    {!! Form::text('3tt', old('3tt'), ['class' => 'form-control']) !!}
    @if($errors->has('3tt'))
      <span class="text-danger">{{ $errors->first('3tt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-32 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('3stt', 'Legenda', ['class' => '']) !!}
    {!! Form::text('3stt', old('3stt'), ['class' => 'form-control']) !!}
    @if($errors->has('3stt'))
      <span class="text-danger">{{ $errors->first('3stt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('4tt', 'Inferior 1', ['class' => '']) !!}
    {!! Form::text('4tt', old('4tt'), ['class' => 'form-control']) !!}
    @if($errors->has('4tt'))
      <span class="text-danger">{{ $errors->first('4tt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-42 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('4stt', 'Legenda', ['class' => '']) !!}
    {!! Form::text('4stt', old('4stt'), ['class' => 'form-control']) !!}
    @if($errors->has('4stt'))
      <span class="text-danger">{{ $errors->first('4stt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('5tt', 'Inferior 2', ['class' => '']) !!}
    {!! Form::text('5tt', old('5tt'), ['class' => 'form-control']) !!}
    @if($errors->has('5tt'))
      <span class="text-danger">{{ $errors->first('5tt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-52 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('5stt', 'Legenda', ['class' => '']) !!}
    {!! Form::text('5stt', old('5stt'), ['class' => 'form-control']) !!}
    @if($errors->has('5stt'))
      <span class="text-danger">{{ $errors->first('5stt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-12 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('6tt', 'Inferior 3', ['class' => '']) !!}
    {!! Form::text('6tt', old('6tt'), ['class' => 'form-control']) !!}
    @if($errors->has('6tt'))
      <span class="text-danger">{{ $errors->first('6tt') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-62 col-md-6">
  <div class="form-group mb-6">
    {!! Form::label('6stt', 'Legenda', ['class' => '']) !!}
    {!! Form::text('6stt', old('6stt'), ['class' => 'form-control']) !!}
    @if($errors->has('6stt'))
      <span class="text-danger">{{ $errors->first('6stt') }}</span>
    @endif
  </div>
</div>

resources/views/admin/empPhoto/create.blade.php
@extends('admin.layouts.default')

@section('content')

{!! Form::open(['method' => 'POST', 'role' => 'form', 'class' => 'form', 'route' => ['admin.emp.photo.store', $emp], 'files' => true]) !!}
<section class="section">
  <div class="section-header mb-0">
    <h1>Nova Foto</h1>
    <div class="section-header-button mr-2">
    </div>
  </div>

  <div class="section-options">
    <div class="text-right mb-2">
      
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header -warning">
            <h4>
              <i class="fas fa-info-circle lga"></i>
              Dados
            </h4>
          </div>
          <div class="card-body">
            <div class="row">
              @include('admin.empPhoto._form')

              <a href="{{ route('admin.emp.photo.index', $emp) }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
              <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
            </div>
          </div>

        </div>
      </div>
  </div>
</section>
{!! Form::close() !!}

@endsection

resources/views/admin/empPhoto/edit.blade.php
@extends('admin.layouts.default')

@section('content')

{!! Form::model($data, ['method' => 'POST', 'role' => 'form', 'class' => 'form', 'route' => ['admin.emp.photo.update', $emp, $data->id], 'files' => true]) !!}
<section class="section">
  <div class="section-header mb-0">
    <h1>Editar Foto</h1>
    <div class="section-header-button mr-2">
    </div>
  </div>

  <div class="section-options">
    <div class="text-right mb-2">
      
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header -warning">
            <h4>
              <i class="fas fa-info-circle lga"></i>
              Dados pessoais
            </h4>
          </div>
          <div class="card-body">
            <div class="row">
              @include('admin.empPhoto._form')

              <a href="{{ route('admin.emp.photo.index', $emp) }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
              <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
            </div>
          </div>

        </div>
      </div>
  </div>
</section>
{!! Form::close() !!}

@endsection

resources/views/admin/empPhoto/index.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Fotos</h1>
      <div class="section-header-button mr-2">
        <a href="{{ route('admin.emp.photo.create', $emp) }}" class="btn btn-success btn-icon btn-lg" title="Adicionar"> <i class="fas fa-plus"></i> Adicionar</a>
        <a href="{{ route('admin.emp.admin') }}" class="btn btn-primary btn-icon btn-lg" title="Adicionar"> <i class="fas fa-arrow-left"></i> Voltar</a>
      </div>
  </div>

  <div class="section-body">
    <div class="row mt-4">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4>
              <i class="far fa-user lga"></i>
              Listagem<br>
              <small>{{ $data->total() }} resultados.</small>
            </h4>
          </div>
          <div class="card-body -table">
            <div class="table-responsive">
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th>#</th>
                    <th>Tipo</th>
                    <th>Imagem</th>
                    <th>Ordem</th>
                    <th>Ações</th>
                  </tr>
                  @foreach($data as $d)
                    <tr>
                      <td>{{ $d->id }}</td>
                      <td>{{ $d->type }}</td>
                      <td>@if($d->img) <img src="{{url('storage/emp/'.$d->img)}}" width="150px"> @endif</td>
                      <td>{{$d->order}}</td>
                      {!! Form::open(['route' => ['admin.emp.photo.destroy', $emp, $d->id]]) !!}
                      <td class="no-wrap">
                        <a href="{{ route('admin.emp.photo.show', [$emp, $d->id]) }}" class="btn btn-success">Editar</a> | 
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Essa ação não pode ser desfeita!')">Apagar</button>
                      </td>
                      {!! Form::close() !!}
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer">
            <div class="float-right">
              <nav>
                {!! $data->render() !!}
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection