routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'laravel-filemanager'], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
Route::get('robots.txt', 'RobotsController');
Route::get('sitemap', 'HomeController@sitemap');

Route::name('home')->get('/', 'HomeController@index');
Route::name('404')->get('/404', 'HomeController@notFound');
Route::name('empreendimentos')->get('empreendimentos', 'EmpController@index');
Route::name('emp')->get('empreendimentos/{slug}', 'EmpController@slug');
Route::name('emp.download')->get('empreendimentos/{slug}/download', 'EmpController@download');
Route::name('emp.contact')->post('empreendimentos/{slug}/contato', 'EmpController@contact');
Route::name('about')->get('/sobre', 'AboutController@index');
Route::name('builder')->get('/monteoseu', 'BuilderController@index');
Route::name('contact')->get('/contato', 'ContactController@index');
Route::name('contact.send')->post('/contato', 'ContactController@store');

Route::name('conteudo')->get('conteudos/{slug}', 'ConteudosController@slug');
Route::name('conteudos')->get('conteudos', 'ConteudosController@index');

Auth::routes(['register' => false]);

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('panel');

    Route::prefix('home')->name('home.')->group(function () {
        Route::get('create', 'AdminController@create')->name('create');
        Route::post('store', 'AdminController@store')->name('store');
        Route::post('{id}/destroy', 'AdminController@destroy')->name('destroy');
        Route::get('{id}', 'AdminController@show')->name('show');
        Route::post('{id}', 'AdminController@update')->name('update');
        Route::get('/', 'AdminController@home')->name('index');
    });
    Route::prefix('destaques')->name('feat.')->group(function () {
        Route::get('create', 'FeatureController@create')->name('create');
        Route::post('store', 'FeatureController@store')->name('store');
        Route::post('{id}/destroy', 'FeatureController@destroy')->name('destroy');
        Route::get('{id}', 'FeatureController@show')->name('show');
        Route::post('{id}', 'FeatureController@update')->name('update');
        Route::get('/', 'FeatureController@index')->name('index');
    });
    Route::prefix('empreendimentos')->name('emp.')->group(function () {
        Route::get('create', 'EmpController@create')->name('create');
        Route::post('store', 'EmpController@store')->name('store');
        Route::post('{id}/destroy', 'EmpController@destroy')->name('destroy');
        Route::get('{id}', 'EmpController@show')->name('show');
        Route::post('{id}', 'EmpController@update')->name('update');
        Route::get('/', 'EmpController@admin')->name('admin');

        Route::get('{emp}/fotos/create', 'EmpPhotoController@create')->name('photo.create');
        Route::post('{emp}/fotos/store', 'EmpPhotoController@store')->name('photo.store');
        Route::post('{emp}/fotos/{id}/destroy', 'EmpPhotoController@destroy')->name('photo.destroy');
        Route::get('{emp}/fotos/{id}', 'EmpPhotoController@show')->name('photo.show');
        Route::post('{emp}/fotos/{id}', 'EmpPhotoController@update')->name('photo.update');
        Route::get('{emp}/fotos', 'EmpPhotoController@index')->name('photo.index');

        Route::get('{emp}/pavimentos/create', 'EmpFloorController@create')->name('floor.create');
        Route::post('{emp}/pavimentos/store', 'EmpFloorController@store')->name('floor.store');
        Route::post('{emp}/pavimentos/{id}/destroy', 'EmpFloorController@destroy')->name('floor.destroy');
        Route::get('{emp}/pavimentos/{id}', 'EmpFloorController@show')->name('floor.show');
        Route::post('{emp}/pavimentos/{id}', 'EmpFloorController@update')->name('floor.update');
        Route::get('{emp}/pavimentos', 'EmpFloorController@index')->name('floor.index');

        Route::get('{emp}/pagamentos/create', 'EmpPaymentController@create')->name('payment.create');
        Route::post('{emp}/pagamentos/store', 'EmpPaymentController@store')->name('payment.store');
        Route::post('{emp}/pagamentos/{id}/destroy', 'EmpPaymentController@destroy')->name('payment.destroy');
        Route::get('{emp}/pagamentos/{id}', 'EmpPaymentController@show')->name('payment.show');
        Route::post('{emp}/pagamentos/{id}', 'EmpPaymentController@update')->name('payment.update');
        Route::get('{emp}/pagamentos', 'EmpPaymentController@index')->name('payment.index');
    });

    Route::prefix('pins')->name('pin.')->group(function () {
        Route::get('create', 'PinController@create')->name('create');
        Route::post('store', 'PinController@store')->name('store');
        Route::post('{id}/destroy', 'PinController@destroy')->name('destroy');
        Route::get('{id}', 'PinController@show')->name('show');
        Route::post('{id}', 'PinController@update')->name('update');
        Route::get('/', 'PinController@index')->name('index');

        Route::get('{pin}/ad/create', 'PinAdController@create')->name('ad.create');
        Route::post('{pin}/ad/store', 'PinAdController@store')->name('ad.store');
        Route::post('{pin}/ad/{id}/destroy', 'PinAdController@destroy')->name('ad.destroy');
        Route::get('{pin}/ad/{id}', 'PinAdController@show')->name('ad.show');
        Route::post('{pin}/ad/{id}', 'PinAdController@update')->name('ad.update');
        Route::get('{pin}/ad', 'PinAdController@index')->name('ad.index');
    });

    Route::prefix('pavimentos')->name('unity.')->group(function () {
        Route::get('{floor}/unidades/create', 'EmpFloorUnityController@create')->name('create');
        Route::post('{floor}/unidades/store', 'EmpFloorUnityController@store')->name('store');
        Route::post('{floor}/unidades/{id}/destroy', 'EmpFloorUnityController@destroy')->name('destroy');
        Route::get('{floor}/unidades/{id}', 'EmpFloorUnityController@show')->name('show');
        Route::post('{floor}/unidades/{id}', 'EmpFloorUnityController@update')->name('update');
        Route::get('{floor}/unidades', 'EmpFloorUnityController@index')->name('index');
    });

    Route::prefix('unidades')->name('planned.')->group(function () {
        Route::get('{p}/planejados/create', 'EmpFloorUnityPlannedController@create')->name('create');
        Route::post('{p}/planejados/store', 'EmpFloorUnityPlannedController@store')->name('store');
        Route::post('{p}/planejados/{id}/destroy', 'EmpFloorUnityPlannedController@destroy')->name('destroy');
        Route::get('{p}/planejados/{id}', 'EmpFloorUnityPlannedController@show')->name('show');
        Route::post('{p}/planejados/{id}', 'EmpFloorUnityPlannedController@update')->name('update');
        Route::get('{p}/planejados', 'EmpFloorUnityPlannedController@index')->name('index');
    });

    Route::prefix('blog')->name('blog.')->group(function () {
        Route::get('create', 'BlogController@create')->name('create');
        Route::post('store', 'BlogController@store')->name('store');
        Route::post('{id}/destroy', 'BlogController@destroy')->name('destroy');
        Route::get('{id}', 'BlogController@show')->name('show');
        Route::post('{id}', 'BlogController@update')->name('update');
        Route::get('/', 'BlogController@index')->name('index');
    });

    Route::prefix('contatos')->name('contact.')->group(function () {
        Route::get('create', 'ContactController@create')->name('create');
        Route::post('store', 'ContactController@store')->name('store');
        Route::post('{id}/destroy', 'ContactController@destroy')->name('destroy');
        Route::get('{id}/simulation', 'ContactController@simulation')->name('simulation');
        Route::get('{id}', 'ContactController@show')->name('show');
        Route::post('{id}', 'ContactController@update')->name('update');
        Route::get('/', 'ContactController@admin')->name('admin');
    });

    Route::prefix('eletros')->name('electro.')->group(function () {
        Route::get('create', 'ElectroController@create')->name('create');
        Route::post('store', 'ElectroController@store')->name('store');
        Route::post('{id}/destroy', 'ElectroController@destroy')->name('destroy');
        Route::get('{id}', 'ElectroController@show')->name('show');
        Route::post('{id}', 'ElectroController@update')->name('update');
        Route::get('/', 'ElectroController@index')->name('index');
    });

    Route::prefix('sobre')->name('about.')->group(function () {
        Route::get('create', 'AboutController@create')->name('create');
        Route::post('store', 'AboutController@store')->name('store');
        Route::post('{id}/destroy', 'AboutController@destroy')->name('destroy');
        Route::get('{id}', 'AboutController@show')->name('show');
        Route::post('{id}', 'AboutController@update')->name('update');
        Route::get('/', 'AboutController@admin')->name('admin');
    });
});

resources/views/admin/partials/_maskmoney.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js"></script>

<script>
  $(function() {
    $('#currency').maskMoney({prefix:'R$ ', allowNegative: true, thousands:'.', decimal:',', affixesStay: false});
    @if(isset($data))
        $("#currency").focus();
    @endif
  });
</script>

resources/views/admin/partials/breadcrumbs.blade.php
@if(Agent::isDesktop())
@if (count($breadcrumbs))
  <div class="section-header-breadcrumb">
    @foreach ($breadcrumbs as $breadcrumb)
      @if ($breadcrumb->url && !$loop->last)
        <div class="breadcrumb-item">
          <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
        </div>
      @else
        <div class="breadcrumb-item breadcrumb-active">
          <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
        </div>
      @endif
    @endforeach
  </div>
@endif
@endif

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
  <div class="footer-left">
    Copyright &copy; {{ date('Y')}}
    <div class="bullet"></div> Desenvolvido e mantido por  <a href="https://qualitare.com/">Qualitare</a>
  </div>
  <div class="footer-right">
    1.0.0
  </div>
</footer>

resources/views/admin/partials/nav.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
      <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
    </ul>
  </form>
  <ul class="navbar-nav navbar-right">
    @auth()
    <li class="dropdown">
      <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
      <div class="d-sm-none d-lg-inline-block">Olá, {{ auth()->user()->name }}</div></a>
      {!! Form::open(['route' => 'logout']) !!}
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-divider"></div>
        <button type="submit" class="dropdown-item has-icon text-danger">
          <i class="fas fa-sign-out-alt"></i> Logout
        </button>
      </div>
      {!! Form::close() !!}
    </li>
    @endauth
  </ul>
</nav>

resources/views/admin/partials/placeable.blade.php
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4>Endereço</h4>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-12 col-md-3">
            <div class="form-group mb-4">
              {!! Form::hidden('address[id]', isset($result->placeable) ? $result->placeable->id : null) !!}
              {!! Form::label('address[cep]', 'CEP', ['class' => '']) !!}
              {!! Form::text('address[cep]', isset($result->placeable) ? $result->placeable->cep : old('address[cep]'), ['class' => 'form-control js-mask-cep', 'id' => 'cep']) !!}
              @if($errors->has('address.cep'))
                <span class="text-danger">{{ $errors->first('address.cep') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-9">
            <div class="form-group mb-4">
              {!! Form::label('address[street]', 'Rua', ['class' => '']) !!}
              {!! Form::text('address[street]', isset($result->placeable) ? $result->placeable->street : old('address[street]'), ['class' => 'form-control', 'id' => 'rua']) !!}
              @if($errors->has('address.street'))
                <span class="text-danger">{{ $errors->first('address.street') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-5">
            <div class="form-group mb-4">
              {!! Form::label('address[neighborhood]', 'Bairro', ['class' => '']) !!}
              {!! Form::text('address[neighborhood]', isset($result->placeable) ? $result->placeable->neighborhood : old('address[neighborhood]'), ['class' => 'form-control', 'id' => 'bairro']) !!}
              @if($errors->has('address.neighborhood'))
                <span class="text-danger">{{ $errors->first('address.neighborhood') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-5">
            <div class="form-group mb-4">
              {!! Form::label('address[complement]', 'Complemento', ['class' => '']) !!}
              {!! Form::text('address[complement]', isset($result->placeable) ? $result->placeable->complement : old('address[complement]'), ['class' => 'form-control']) !!}
              @if($errors->has('address.complement'))
                <span class="text-danger">{{ $errors->first('address.complement') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-2">
            <div class="form-group mb-4">
              {!! Form::label('address[number]', 'Número', ['class' => '']) !!}
              {!! Form::text('address[number]', isset($result->placeable) ? $result->placeable->number : old('address[number]'), ['class' => 'form-control']) !!}
              @if($errors->has('address.number'))
                <span class="text-danger">{{ $errors->first('address.number') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-3">
            <div class="form-group mb-4">
              {!! Form::label('address[city]', 'Cidade', ['class' => '']) !!}
              {!! Form::text('address[city]', isset($result->placeable) ? $result->placeable->city : old('address[city]'), ['class' => 'form-control', 'id' => 'localidade']) !!}
              @if($errors->has('address.city'))
                <span class="text-danger">{{ $errors->first('address.city') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-2">
            <div class="form-group mb-4">
              {!! Form::label('address[state]', 'Estado', ['class' => '']) !!}
              {!! Form::text('address[state]', isset($result->placeable) ? $result->placeable->state : old('address[state]'), ['class' => 'form-control', 'id' => 'uf']) !!}
              @if($errors->has('address.state'))
                <span class="text-danger">{{ $errors->first('address.state') }}</span>
              @endif
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/admin/partials/scripts.blade.php
<!-- General JS Scripts -->
{{-- <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script> --}}
@jquery
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
{{-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> --}}

<script src="{{asset('assets_front/js/bootstrap.js')}}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js"></script>

<script src="{{ asset('/assets/js/mask.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/pt.js"></script>


<script src="{{ asset('/assets/js/stisla.js') }}"></script>
<!-- JS Libraies -->

<!-- Template JS File -->
<script src="{{ asset('/assets/js-duallistbox/jquery.bootstrap-duallistbox.js') }}"></script>
<script src="{{ asset('/assets/js/scripts.js') }}"></script>
<script src="{{ asset('/assets/js/custom.js') }}"></script>
<script src="{{ asset('/assets/js/cep.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.26.14/sweetalert2.all.min.js"></script>
<script src="{{ asset('/assets/js/admin.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.js"></script>
<script src="{{ asset('/assets/js/sortable.js') }}"></script>

resources/views/admin/partials/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand mb-2">
      <a href="{{ route('admin.panel') }}"><img src="{{ asset('/assets/img/brand.svg') }}" width="50"></a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href="{{ route('admin.panel') }}"><img src="{{ asset('/assets/img/brand.svg') }}" width="50"></a>
    </div>
    <ul class="sidebar-menu">
      <li class="menu-header">Módulos</li>
      <li class="dropdown ">
        <a href="#" class="nav-link has-dropdown">
          <i class=" far fa-star lga"></i>
          <span>Home</span>
        </a>
        <ul class="dropdown-menu" style="display: none;">
          <li>
            <a class="nav-link" href="{{ route('admin.home.index') }}" title="Home">Home</a>
          </li>
          <li>
            <a class="nav-link" href="{{ route('admin.feat.index') }}" title="Destaque">Destaques</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="{{ route('admin.about.admin') }}">
          <i class="far fa-star lga"></i>
          <span>Sobre</span>
        </a>
      </li>
      <li>
        <a href="{{ route('admin.pin.index') }}">
          <i class="far fa-star lga"></i>
          <span>Pins</span>
        </a>
      </li>
      <li class="dropdown ">
        <a href="#" class="nav-link has-dropdown">
          <i class=" far fa-star lga"></i>
          <span>Empreendimentos</span>
        </a>
        <ul class="dropdown-menu" style="display: none;">
          <li>
            <a class="nav-link" href="{{ route('admin.emp.admin') }}" title="Home">Imóveis
            </a>
          </li>
          <li>
            <a class="nav-link" href="{{ route('admin.electro.index') }}" title="Destaque">Eletrodomésticos</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="{{ route('admin.blog.index') }}">
          <i class="far fa-star lga"></i>
          <span>Conteúdos</span>
        </a>
      </li>
      <li>
        <a href="{{ route('admin.contact.admin') }}">
          <i class="far fa-star lga"></i>
          <span>Contatos</span>
        </a>
      </li>
    </ul>
  </aside>
</div>

resources/views/admin/partials/styles.blade.php
<!-- General CSS Files -->
<link rel="stylesheet" href="{{ asset('/assets/modules/bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('/assets/modules/bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('/assets/modules/fontawesome/css/all.min.css') }}?ver=10.0">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.css">

<!-- CSS Libraries -->

<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('/assets/css/components.css') }}">
<link rel="stylesheet" href="{{ asset('/assets/css/style.css') }}?ver=10.0">
<link rel="stylesheet" href="{{ asset('/assets/css/custom.css') }}?ver=10.0">
<link rel="stylesheet" href="{{ asset('/assets/js-duallistbox/bootstrap-duallistbox.min.css') }}">
<link rel="stylesheet" href="{{asset('assets_front/icon-fonts/css/style.css')}}?ver=10.0">